name: ml_tooling_tutorial
channels:
  - conda-forge
  - nodefaults # be strict: do not include the "defaults" channel

dependencies:
  # core interpreter
  - python=3.12
  # dev & code-quality
  - mamba
  - pylint
  - pytest
  - pytest-cov
  - black
  - pathspec
  - isort
  - mypy
  - ipykernel
  - tqdm
  - gitpython
  - pydantic>=2.11
  - pyyaml
  - joblib
  # science stack
  - matplotlib
  - numpy
  - scipy
  - pandas
  - scikit-learn
  # MLOps
  - mlflow
  - dvc
  - optuna
  - optuna-dashboard
  - plotly # for optuna visualization
  - python-kaleido # for plotly
  # pip
  - pip
  - pip:
      - types-PyYAML
      - psutil # for system metrics by mlflow
      - prefect==3.*
